### PR TITLE
Database url now pointing to remote server

### PR DESCRIPTION
**Pull request by bookdude13**
Database now located on a Digital Ocean droplet. Talk to me if you want access to it.

P.S. only looking for one review, although multiple are fine :)

### CODE REVIEW

**Review by computergeek125 — CHANGES_REQUESTED** [review]
Don't EVER send database queries over an unencrypted connection across the internet.  Intranet queries are fine.  Likewise, never allow a database to listen on an internet link.

**Comment by computergeek125** [comment]
Preface: I've only read through this commit and file.  This is an IT-related fix.  If you want to do this architecture, do an API of some kind over HTTPS so that things are encrypted, or require users to connect to a VPN first.  I can give you access to my server (don't steal it :P) if you want to see how to set that up.  

If you go the VPN route, have your VPN software create a special IP address listening on a dedicated TUN device, and set Postgres to ONLY listen on that IP, and create a digital ocean firewall and/or use UFW to restrict access to only SSH, HTTP(S), and any VPN ports.

If you go the HTTP route, the helper application listens on HTTP(s) (if HTTP have nginx terminate HTTPS), and then queries the Postgres database (which then listens only on localhost) based on the API input.

**Comment by computergeek125** [comment]
Also: since the IP is published in git, you're going to want to harden that server a LOT

**Comment by bookdude13** [comment]
Is this acceptable to you @computergeek125? The only way the password is obtained is if it is told in person, and it's stored outside of the version controlled directory. My bad initially

**Comment by bookdude13** [comment]
Right now I restricted the IP addresses allowed to connect. @computergeek125 when you get a chance can you try connecting again? Should be denied. And I agree that this should be made more secure (SSL/TLS connection, whatever). Considering we're a low-value target, the light show is in a month, and we need to get rolling on this, I think this is fine for now. Risk analysis tells me to move forward.

**Comment by bookdude13** [comment]
Pulling in for now. Yell at me to change it if you disagree

**Comment by bookdude13** [comment]
Addresses #62

**Pull request merged**
